---
title: "streams"
output:
  github_document: default
---

These are preliminary graphs of stream chemistry.  
Additional figures, presented at the 2019 SFS conference, can be found [here](https://github.com/kaizadp/bbwm_recovery_cations/blob/master/sfs2019/sfs2019_graphs.md).



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>"
                      #fig.path = "images/fticr_markdown/"
                      )

library(tidyverse)
library(lubridate)
library(soilpalettes)
```

```{r}
streams = read.csv("data/bbwm_stream_chemistry_1988_2019.csv") %>% 
  dplyr::mutate(Date = ymd(Date)) %>% 
  filter(Watershed %in% c("EB", "WB"))
```

## all time series

```{r timeseries, fig.width=15, fig.height=15}
streams %>% 
  dplyr::select(
    Watershed, Date,
    Ca_ueq_L, Mg_ueq_L, K_ueq_L, Na_ueq_L,
    NO3_ueq_L, SO4_ueq_L,NH4_ueq_L, total_N_ppm,
    DOC_mg_L, DIC_mg_L,
    Al_ppb, Al_org_ppb,
    Cl_ueq_L, Si_mg_L,
    total_P_ppb, H_ueq_L,
    ANC_ueq_L, HCO3_ueq_L,
    sp_conductance_us_cm) %>% 
  pivot_longer(-c("Watershed", "Date"),
              names_to = "species") %>%
  dplyr::mutate(species = factor(species, 
                                 levels = 
                                   c("Ca_ueq_L", "Mg_ueq_L", "K_ueq_L", "Na_ueq_L",
    "NO3_ueq_L", "SO4_ueq_L","NH4_ueq_L", "total_N_ppm",
    "DOC_mg_L", "DIC_mg_L",
    "Al_ppb", "Al_org_ppb",
    "Cl_ueq_L", "Si_mg_L",
    "total_P_ppb", "H_ueq_L",
    "ANC_ueq_L", "HCO3_ueq_L",
    "sp_conductance_us_cm"))) %>% 
  ggplot(aes(x = Date, y = value, color = Watershed, shape = Watershed))+
  geom_point()+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+  
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  facet_wrap(~species, scales = "free_y", ncol = 4)+
  labs(x = "")+
  theme_bw()+
  theme(legend.position = "top")+
  NULL
```


---

### ANNUAL EXPORT

```{r}
streams_annual = read.csv("data/annual_outflux.csv", stringsAsFactors = F)
```

```{r exports, fig.width=15, fig.height=10}
(exports = 
  streams_annual %>%
  dplyr::select(-Area, -H2O) %>% 
  pivot_longer(-c("Watershed", "WY"),
              names_to = "species") %>% 
   filter(!is.na(species)) %>% 
  dplyr::mutate(species = factor(species, levels = c("Ca", "Mg", "Na", "K",
                                                     "SO4", "NO3", "NH4",
                                                     "DOC", "Al", "H","Cl","Si",
                                                     "ANC", "HCO3","Discharge.L.s","EQPH"))) %>% 
  ggplot(aes(x = WY, y = value, color = Watershed, shape = Watershed))+
  geom_point()+
  geom_vline(xintercept = 2016.5, linetype = "dashed")+  
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  facet_wrap(~species, scales = "free_y", ncol = 4)+
  labs(x = "")+
  theme_bw()+
  theme(legend.position = "top")+
  NULL
)
```




### base cations

```{r cation_dumbell}
streams %>% 
  dplyr::select(Watershed, Date, Year,
                Ca_ueq_L, Mg_ueq_L, Na_ueq_L, K_ueq_L) %>% 
  pivot_longer(-c("Watershed", "Date", "Year"),
               values_to = "ueq_L",
               names_to = "ion") %>%
  #na.omit() %>% 
  ggplot(aes(x = Date, ueq_L,
             color = Watershed, shape = Watershed))+
  geom_point()+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  facet_wrap(~ion, scales = "free_y")+
  theme_bw()
```



```{r}
streams %>% 
  dplyr::select(Watershed, Date, Year,
                Ca_ueq_L, Mg_ueq_L, Na_ueq_L, K_ueq_L) %>% 
  pivot_longer(-c("Watershed", "Date", "Year"),
               values_to = "ueq_L",
               names_to = "ion") %>% 
  
  ggplot(aes(x = Date, ueq_L,
             color = Watershed, shape = Watershed))+
  geom_point()+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  facet_wrap(~ion, scales = "free_y")+
  theme_bw()
```

### acid anions

```{r, fig.height=3.5, fig.width=6}
streams %>% 
  dplyr::select(Watershed, Date, NO3_ueq_L, SO4_ueq_L) %>% 
  pivot_longer(-c("Watershed", "Date"),
               values_to = "ueq_L",
               names_to = "ion") %>% 
  ggplot(aes(x = Date, y = ueq_L, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  facet_wrap(~ion, scales = "free_y")+
  theme_bw()+
  theme(legend.position = "top")

```


### DOC  

```{r}
streams %>% 
  ggplot(aes(x = Date, y = DOC_mg_L, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()

```

```{r}
streams %>% 
  ggplot(aes(x = Date, y = SUVA, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()+
  labs(title = "specific UV absorbance of DOC",
       subtitle = "higher SUVA = more aromatic, more terrestrial?")
```

### aluminum

```{r}
streams %>% 
  ggplot(aes(x = Date, y = Al_ppb, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()
```

```{r}
streams %>% 
  ggplot(aes(x = Date, y = Al_org_ppb, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()
```

### pH -- so many pHs!

```{r}
streams %>% 
  dplyr::select(Watershed, Date, starts_with("pH")) %>% 
  pivot_longer(-c("Watershed", "Date"),
               values_to = "pH",
               names_to = "type") %>% 
  ggplot(aes(x = Date, y = pH, color = Watershed, shape=Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+

  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  facet_wrap(~type)+
  theme_bw()
```

```{r}
streams %>% 
  ggplot(aes(x = pH_air_eqll, y = pH_closed_cell, color = Watershed, shape = Watershed))+
  geom_point(size=2)+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  labs(title="comparing pH types")+
  theme_bw()
```

```{r}
streams %>% 
  ggplot(aes(x = Date, y = H_ueq_L, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()
```

### others

```{r}
streams %>% 
  ggplot(aes(x = Date, y = ANC_ueq_L, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()
```

```{r}
streams %>% 
  ggplot(aes(x = Date, y = HCO3_ueq_L, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()
```

```{r}
streams %>% 
  ggplot(aes(x = Date, y = sp_conductance_us_cm, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()
```

```{r}
streams %>% 
  ggplot(aes(x = Date, y = total_P_ppb, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()
```

```{r}
streams %>% 
  ggplot(aes(x = Date, y = Cl_ueq_L, color = Watershed, shape = Watershed))+
  geom_point()+
  scale_color_manual(values = c("grey70", "darkred"))+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = as.Date("2016-10-31"), linetype = "dashed")+
  theme_bw()
```

---

**Session Info**  
Date run: `r Sys.Date()`  
```{r}
sessionInfo()
```



